site_name: Documentação - Monitoramento de Carbono
site_author: Felipe Jesus
site_url: 'https://FelipeJesusRemoteSensing.github.io/CarbonProgram/'
repo_url: 'https://github.com/FelipeJesusRemoteSensing/CarbonProgram'
repo_name: 'CarbonProgram'
theme:
  name: readthedocs

extra_css:
  - stylesheets/extra.css
 
nav:
  - 'Home': 'index.md'
  - 'Contexto': 'mds/contexto.md'
  - 'Referências Conceituais': 'mds/referencias_conceituais.md'